export const restaurants = [
  {
    id: 1,
    name: 'Günaydın Steakhouse',
    type: 'kebab',
    rating: 4.8,
    reviews: 342,
    distance: '0.5 km',
    deliveryTime: '25-35 dk',
    image: require('../../assets/steakhouse.jpeg'),
    isOpen: true,
    isFavorite: false,
    category: 'fast-food',
    isSelfService: false,
    coordinate: {
      latitude: 41.6781,
      longitude: 26.5567,
    },
    address: 'Saraçlar Caddesi No:15, Edirne',
    phone: '+90 284 212 34 56',
    workingHours: '11:00 - 23:00',
    description: 'Edirne\'nin en kaliteli et restoranı. Taze et çeşitleri ve özel soslarımızla unutulmaz lezzetler sunuyoruz.',
    features: ['Rezervasyon', 'Açık Alan', 'Otopark', 'WiFi', 'Kredi Kartı'],
    priceRange: '₺₺₺',
    minOrder: 75
  },
  {
    id: 2,
    name: 'Pizza Palace',
    type: 'fast-food',
    rating: 4.6,
    reviews: 128,
    distance: '0.8 km',
    deliveryTime: '20-30 dk',
    image: require('../../assets/pizza.jpeg'),
    isOpen: true,
    isFavorite: true,
    category: 'fast-food',
    isSelfService: true,
    coordinate: {
      latitude: 41.6761,
      longitude: 26.5547,
    },
    address: 'Selimiye Camii yakını, Mimar Sinan Cd. No:42, Edirne',
    phone: '+90 284 225 67 89',
    workingHours: '12:00 - 24:00',
    description: 'Geleneksel İtalyan pizzaları ve makarna çeşitleriyle hizmet veren aile restoranı.',
    features: ['Self Servis', 'WiFi', 'Çocuk Menüsü', 'Kredi Kartı'],
    priceRange: '₺₺',
    minOrder: 45
  },
  {
    id: 3,
    name: 'Sushi Master',
    type: 'asian-food',
    rating: 4.9,
    reviews: 89,
    distance: '1.2 km',
    deliveryTime: '30-40 dk',
    image: require('../../assets/sushi.jpeg'),
    isOpen: false,
    isFavorite: false,
    category: 'asian-food',
    isSelfService: false,
    coordinate: {
      latitude: 41.6668,
      longitude: 26.5702,
    },
    address: 'Erasta Yanı , Edirne Merkez',
    phone: '+90 284 234 12 45',
    workingHours: '17:00 - 23:00',
    description: 'Taze balıklar ve geleneksel Japon usulü hazırlanan sushilerimizle benzersiz bir deneyim yaşayın.',
    features: ['Rezervasyon', 'Nehir Manzarası', 'Otopark', 'WiFi', 'Kredi Kartı'],
    priceRange: '₺₺₺₺',
    minOrder: 120
  },
  {
    id: 5,
    name: 'Burger Yiyelim',
    type: 'fast-food',
    rating: 4.6,
    reviews: 128,
    distance: '0.8 km',
    deliveryTime: '20-30 dk',
    image: require('../../assets/pizza.jpeg'),
    isOpen: true,
    isFavorite: true,
    category: 'fast-food',
    isSelfService: true,
    coordinate: {
      latitude: 41.6761,
      longitude: 26.5547,
    },
    address: 'Selimiye Camii yakını, Mimar Sinan Cd. No:42, Edirne',
    phone: '+90 284 225 67 89',
    workingHours: '12:00 - 24:00',
    description: 'Geleneksel İtalyan pizzaları ve makarna çeşitleriyle hizmet veren aile restoranı.',
    features: ['Self Servis', 'WiFi', 'Çocuk Menüsü', 'Kredi Kartı'],
    priceRange: '₺₺',
    minOrder: 45
  },
  {
    id: 6,
    name: 'Pizza Oktay',
    type: 'fast-food',
    rating: 4.6,
    reviews: 128,
    distance: '0.8 km',
    deliveryTime: '20-30 dk',
    image: require('../../assets/pizza.jpeg'),
    isOpen: true,
    isFavorite: true,
    category: 'fast-food',
    isSelfService: true,
    coordinate: {
      latitude: 41.6761,
      longitude: 26.5547,
    },
    address: 'Selimiye Camii yakını, Mimar Sinan Cd. No:42, Edirne',
    phone: '+90 284 225 67 89',
    workingHours: '12:00 - 24:00',
    description: 'Geleneksel İtalyan pizzaları ve makarna çeşitleriyle hizmet veren aile restoranı.',
    features: ['Self Servis', 'WiFi', 'Çocuk Menüsü', 'Kredi Kartı'],
    priceRange: '₺₺',
    minOrder: 45
  },
  {
    id: 7,
    name: 'Espresso Tech',
    type: 'cafe',
    rating: 0,
    reviews: 0,
    distance: '',
    deliveryTime: '',
    image: require('../../assets/icon.png'),
    isOpen: true,
    isFavorite: false,
    category: 'cafe',
    isSelfService: false,
    coordinate: {
      latitude: 41.6346,
      longitude: 26.6208,
    },
    address: 'Trakya Üniversitesi Mühendislik Fakültesi Yanı, Edirne Merkez',
    phone: '',
    workingHours: '08:00 - 22:00',
    description: 'Teknoloji ve kahve buluşma noktası. Modern çalışma alanı ve taze kahveler.',
    features: ['WiFi', 'Çalışma Alanı', 'Kredi Kartı'],
    priceRange: '₺₺',
    minOrder: 0
  },
  {
     id: 8,
    name: 'Pasta Dünyası',
    type: 'dessert',
    rating: 0,
    reviews: 0,
    distance: '',
    deliveryTime: '',
    image: require('../../assets/icon.png'),
    isOpen: true,
    isFavorite: false,
    category: 'cafe',
    isSelfService: false,
    coordinate: {
      latitude: 41.6676,
      longitude: 26.5774,
    },
    address: 'Pastane Ayşekadın, Edirne Merkez',
    phone: '',
    workingHours: '08:00 - 22:00',
    description: 'Teknoloji ve kahve buluşma noktası. Modern çalışma alanı ve taze kahveler.',
    features: ['WiFi', 'Çalışma Alanı', 'Kredi Kartı'],
    priceRange: '₺₺',
    minOrder: 0
  }
];