export const restaurants = [
  {
    id: 1,
    name: 'Günaydın Steakhouse',
    type: 'Et Restoranı',
    rating: 4.8,
    reviews: 342,
    distance: '0.5 km',
    deliveryTime: '25-35 dk',
    image: require('../../assets/steakhouse.jpeg'),
    discount: '20% indirim',
    isOpen: true,
    isFavorite: false,
    category: 'fast-food',
    isSelfService: false,
    coordinate: {
      latitude: 41.6781,
      longitude: 26.5567,
    },
    address: 'Saraçlar Caddesi No:15, Edirne',
    phone: '+90 284 212 34 56',
    workingHours: '11:00 - 23:00',
    description: 'Edirne\'nin en kaliteli et restoranı. Taze et çeşitleri ve özel soslarımızla unutulmaz lezzetler sunuyoruz.',
    features: ['Rezervasyon', 'Açık Alan', 'Otopark', 'WiFi', 'Kredi Kartı'],
    priceRange: '₺₺₺',
    minOrder: 75
  },
  {
    id: 2,
    name: 'Pizza Palace',
    type: 'fast-food',
    rating: 4.6,
    reviews: 128,
    distance: '0.8 km',
    deliveryTime: '20-30 dk',
    image: require('../../assets/pizza.jpeg'),
    discount: '15% indirim',
    isOpen: true,
    isFavorite: true,
    category: 'fast-food',
    isSelfService: true,
    coordinate: {
      latitude: 41.6761,
      longitude: 26.5547,
    },
    address: 'Selimiye Camii yakını, Mimar Sinan Cd. No:42, Edirne',
    phone: '+90 284 225 67 89',
    workingHours: '12:00 - 24:00',
    description: 'Geleneksel İtalyan pizzaları ve makarna çeşitleriyle hizmet veren aile restoranı.',
    features: ['Self Servis', 'WiFi', 'Çocuk Menüsü', 'Kredi Kartı'],
    priceRange: '₺₺',
    minOrder: 45
  },
  {
    id: 3,
    name: 'Sushi Master',
    type: 'asian-food',
    rating: 4.9,
    reviews: 89,
    distance: '1.2 km',
    deliveryTime: '30-40 dk',
    image: require('../../assets/sushi.jpeg'),
    discount: null,
    isOpen: false,
    isFavorite: false,
    category: 'asian-food',
    isSelfService: false,
    coordinate: {
      latitude: 41.6791,
      longitude: 26.5577,
    },
    address: 'Meriç Nehri kenarı, Tunca Cd. No:78, Edirne',
    phone: '+90 284 234 12 45',
    workingHours: '17:00 - 23:00',
    description: 'Taze balıklar ve geleneksel Japon usulü hazırlanan sushilerimizle benzersiz bir deneyim yaşayın.',
    features: ['Rezervasyon', 'Nehir Manzarası', 'Otopark', 'WiFi', 'Kredi Kartı'],
    priceRange: '₺₺₺₺',
    minOrder: 120
  },
];