import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5DC',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  backButton: {
    padding: 8,
  },
  backIcon: {
    fontSize: 24,
    color: '#2C3E50',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
  },
  restaurantInfo: {
    backgroundColor: '#FFFFFF',
    margin: 20,
    padding: 20,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  restaurantName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 5,
  },
  restaurantType: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  cartSection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  summarySection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  tableSection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 15,
  },
  cartItem: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E1E8ED',
  },
  cartItemImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  itemNote: {
    fontSize: 12,
    color: '#7F8C8D',
    marginBottom: 6,
  },
  removeButton: {
    marginLeft: 10,
    padding: 6,
  },
  removeButtonText: {
    fontSize: 18,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 5,
    flexShrink: 1,
  },
  itemPrice: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    // use fixed width so the controls don't squeeze other items and cause wrapping
    width: 110,
    justifyContent: 'center',
  },
  quantityButton: {
    backgroundColor: '#FF6B35',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 6,
  },
  quantityButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  quantityText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C3E50',
    minWidth: 20,
    textAlign: 'center',
  },
  itemTotal: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF6B35',
    width: 80,
    flexShrink: 0,
    textAlign: 'right',
  },
  itemInfo: {
    flex: 1,
    marginRight: 8,
    minWidth: 0, // allow text to truncate instead of pushing layout
  },
  itemPrice: {
    fontSize: 14,
    color: '#7F8C8D',
    flexWrap: 'nowrap',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  summaryLabel: {
    fontSize: 16,
    color: '#7F8C8D',
  },
  summaryValue: {
    fontSize: 16,
    color: '#2C3E50',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#E1E8ED',
    marginTop: 10,
    paddingTop: 15,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  tableInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // replace gap with spacing on children
  },

  paymentSection: {
    marginTop: 12,
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
  },
  paymentRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  paymentLabel: { fontSize: 16, color: '#2C3E50' },
  paymentButton: { backgroundColor: '#FF6B35', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8 },
  paymentButtonText: { color: '#FFFFFF', fontWeight: '700' },
  payModalWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.4)' },
  payModal: { width: '90%', backgroundColor: '#FFF', borderRadius: 12, padding: 20, alignItems: 'center' },
  payTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
  payOption: { width: '100%', paddingVertical: 12, paddingHorizontal: 10, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: '#EEE' },
  payOptionActive: { backgroundColor: '#FF6B35', borderColor: '#FF6B35' },
  payOptionText: { textAlign: 'center', color: '#2C3E50' },
  payOptionTextActive: { color: '#FFF', fontWeight: '700' },
  payClose: { marginTop: 8 },
  payCloseText: { color: '#2C3E50', fontWeight: '700' },
  tableLabel: {
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '500',
  },
  tableInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E1E8ED',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2C3E50',
  },
  clearCartButton: {
    marginTop: 12,
    alignSelf: 'flex-end',
  },
  clearCartText: {
    color: '#E74C3C',
    fontWeight: '700',
  },
  modalContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  modalHeader: { padding: 12, borderBottomWidth: 1, borderBottomColor: '#EEE' },
  modalClose: { color: '#2C3E50', fontWeight: '700' },
  modalContent: { padding: 20, alignItems: 'center' },
  modalImage: { width: 200, height: 200, borderRadius: 12, marginBottom: 12 },
  modalTitle: { fontSize: 20, fontWeight: '700', color: '#2C3E50' },
  modalPrice: { fontSize: 18, fontWeight: '700', color: '#FF6B35', marginBottom: 12 },
  modalQuantityRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  modalQtyButton: { backgroundColor: '#FF6B35', width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  modalQtyText: { color: '#FFFFFF', fontSize: 20, fontWeight: '700' },
  modalQtyValue: { marginHorizontal: 20, fontSize: 18, fontWeight: '700' },
  noteInput: { width: '100%', borderWidth: 1, borderColor: '#E1E8ED', borderRadius: 8, padding: 12, marginBottom: 12 },
  checkoutContainer: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  checkoutButton: {
    backgroundColor: '#FF6B35',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  checkoutButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  emptyCart: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyCartIcon: {
    fontSize: 80,
    marginBottom: 20,
  },
  emptyCartTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 10,
  },
  emptyCartText: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 30,
  },
  browseMenuButton: {
    backgroundColor: '#FF6B35',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 12,
  },
  browseMenuButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
